//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelFinalProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TravelFinalProject.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Tour Operators and Travel Agency. We offering in total 793 tours and holidays throughout the world. Combined we have received 1532 customer reviews and an average rating of 5 out of 5 stars.
        ///
        ///Travel has helped us to understand the meaning of life and it has helped us become better people. Each time we travel, we see the world with new eyes..
        /// </summary>
        public static string AboutP {
            get {
                return ResourceManager.GetString("AboutP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Yatriiworld.
        /// </summary>
        public static string AboutSTitle {
            get {
                return ResourceManager.GetString("AboutSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re truely dedicated to make your travel experience best.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        public static string Adult {
            get {
                return ResourceManager.GetString("Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazing Tours.
        /// </summary>
        public static string AmazingTours {
            get {
                return ResourceManager.GetString("AmazingTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The real voyage does not consist in seeking new landscapes.
        /// </summary>
        public static string Articles1 {
            get {
                return ResourceManager.GetString("Articles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountains is always right destination..
        /// </summary>
        public static string Articles2 {
            get {
                return ResourceManager.GetString("Articles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have not all those who wander are lost..
        /// </summary>
        public static string Articles3 {
            get {
                return ResourceManager.GetString("Articles3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here Our&apos;s Life is either a daring adventure..
        /// </summary>
        public static string Articles4 {
            get {
                return ResourceManager.GetString("Articles4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take only memories, leave only footprints..
        /// </summary>
        public static string Articles5 {
            get {
                return ResourceManager.GetString("Articles5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles &amp; Travel Guidings.
        /// </summary>
        public static string ArticlesAndGuides {
            get {
                return ResourceManager.GetString("ArticlesAndGuides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel has helped us to understand the meaning of life and it has helped us become better people. Each time we travel, we see the world with new eyes..
        /// </summary>
        public static string ArticlesAndGuidesDesc {
            get {
                return ResourceManager.GetString("ArticlesAndGuidesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award Winning Service.
        /// </summary>
        public static string AwardWinningService {
            get {
                return ResourceManager.GetString("AwardWinningService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabulous Travel worry free knowing that we&apos;re here if you need us, 24 hours a day.
        /// </summary>
        public static string AWSDesc {
            get {
                return ResourceManager.GetString("AWSDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio.
        /// </summary>
        public static string Bio {
            get {
                return ResourceManager.GetString("Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogs.
        /// </summary>
        public static string Blogs {
            get {
                return ResourceManager.GetString("Blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check  Availability.
        /// </summary>
        public static string CheckAvailability {
            get {
                return ResourceManager.GetString("CheckAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckIn.
        /// </summary>
        public static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Destination.
        /// </summary>
        public static string ChooseDestination {
            get {
                return ResourceManager.GetString("ChooseDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitive Pricing.
        /// </summary>
        public static string CompetitivePricing {
            get {
                return ResourceManager.GetString("CompetitivePricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CPassword {
            get {
                return ResourceManager.GetString("CPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With 500+ suppliers and the purchasing power of 300 million members.
        /// </summary>
        public static string CPDesc {
            get {
                return ResourceManager.GetString("CPDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Service.
        /// </summary>
        public static string CustomerService {
            get {
                return ResourceManager.GetString("CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel has helped us to understand the meaning of life and it has helped us become better people. Each time we travel, we see the world with new eyes..
        /// </summary>
        public static string Deal {
            get {
                return ResourceManager.GetString("Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save big on hotels!.
        /// </summary>
        public static string Deal1 {
            get {
                return ResourceManager.GetString("Deal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With upto 30% Off, experience Europe your way!.
        /// </summary>
        public static string Deal1Desc {
            get {
                return ResourceManager.GetString("Deal1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earning Asiana Club Miles.
        /// </summary>
        public static string Deal2 {
            get {
                return ResourceManager.GetString("Deal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience Europe Your Way.
        /// </summary>
        public static string Deal3 {
            get {
                return ResourceManager.GetString("Deal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel has helped us to understand the meaning of life and it has helped us become better people. Each time we travel, we see the world with new eyes..
        /// </summary>
        public static string DealDesc {
            get {
                return ResourceManager.GetString("DealDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Top Deal.
        /// </summary>
        public static string DealTitle {
            get {
                return ResourceManager.GetString("DealTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Information.
        /// </summary>
        public static string DeliveryInformation {
            get {
                return ResourceManager.GetString("DeliveryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depart Date.
        /// </summary>
        public static string DepartDate {
            get {
                return ResourceManager.GetString("DepartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel has helped us to understand the meaning of life and it has helped us become better people. Each time we travel, we see the world with new eyes..
        /// </summary>
        public static string destDescription {
            get {
                return ResourceManager.GetString("destDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinations.
        /// </summary>
        public static string Destinations {
            get {
                return ResourceManager.GetString("Destinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Your Favourite Destination.
        /// </summary>
        public static string destTitle {
            get {
                return ResourceManager.GetString("destTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string Discover {
            get {
                return ResourceManager.GetString("Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a places.
        /// </summary>
        public static string FindAPlaces {
            get {
                return ResourceManager.GetString("FindAPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy Customers.
        /// </summary>
        public static string HappyCustomers {
            get {
                return ResourceManager.GetString("HappyCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Business.
        /// </summary>
        public static string InBusiness {
            get {
                return ResourceManager.GetString("InBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to be notified when we launch a new template or an udpate. Just sign up and we&apos;ll send you a notification by email.
        /// </summary>
        public static string NewDes {
            get {
                return ResourceManager.GetString("NewDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NPassword {
            get {
                return ResourceManager.GetString("NPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ou rService.
        /// </summary>
        public static string OurService {
            get {
                return ResourceManager.GetString("OurService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Date.
        /// </summary>
        public static string ReturnDate {
            get {
                return ResourceManager.GetString("ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Policy.
        /// </summary>
        public static string ReturnPolicy {
            get {
                return ResourceManager.GetString("ReturnPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel has helped us to understand the meaning of life and it has helped us become better people. Each time we travel, we see the world with new eyes..
        /// </summary>
        public static string reviewDescription {
            get {
                return ResourceManager.GetString("reviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What People Say About Us.
        /// </summary>
        public static string reviewTitle {
            get {
                return ResourceManager.GetString("reviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Change.
        /// </summary>
        public static string SaveChange {
            get {
                return ResourceManager.GetString("SaveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tour.
        /// </summary>
        public static string SelectTour {
            get {
                return ResourceManager.GetString("SelectTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        public static string SiteMap {
            get {
                return ResourceManager.GetString("SiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMMER SPECIAL UPTO 25% OFF.
        /// </summary>
        public static string Summer {
            get {
                return ResourceManager.GetString("Summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string summerbutton {
            get {
                return ResourceManager.GetString("summerbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEND THE BEST VACATION WITH US
        ///The nights of Thailand.
        /// </summary>
        public static string SummerDesc {
            get {
                return ResourceManager.GetString("SummerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Cases.
        /// </summary>
        public static string SupportCases {
            get {
                return ResourceManager.GetString("SupportCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string Terms_Conditions {
            get {
                return ResourceManager.GetString("Terms&Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Duration.
        /// </summary>
        public static string TotalDuration {
            get {
                return ResourceManager.GetString("TotalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel has helped us to understand the meaning of life and it has helped us become better people. Each time we travel, we see the world with new eyes..
        /// </summary>
        public static string tourDescription {
            get {
                return ResourceManager.GetString("tourDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel
        ///Best Holidays Trips
        ///In The World.
        /// </summary>
        public static string TourDestT {
            get {
                return ResourceManager.GetString("TourDestT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour List.
        /// </summary>
        public static string TourList {
            get {
                return ResourceManager.GetString("TourList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours.
        /// </summary>
        public static string Tours {
            get {
                return ResourceManager.GetString("Tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect Tour Packages.
        /// </summary>
        public static string tourTitle {
            get {
                return ResourceManager.GetString("tourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Photo.
        /// </summary>
        public static string UploadPhoto {
            get {
                return ResourceManager.GetString("UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,200,000 hotels in more than 200 countries and regions &amp; flights to over 5,000 citites..
        /// </summary>
        public static string WCDesc {
            get {
                return ResourceManager.GetString("WCDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worldwide Coverage.
        /// </summary>
        public static string WorldwideCoverage {
            get {
                return ResourceManager.GetString("WorldwideCoverage", resourceCulture);
            }
        }
    }
}
